#include "usb_descriptor_data.h"

#define USB_DESC_DEVICE 0x01u
#define USB_DESC_CONFIGURATION 0x02u
#define USB_DESC_INTERFACE 0x04u
#define USB_DESC_ENDPOINT 0x05u

#define USB_TRANSFER_BULK 0x02u
#define USB_TRANSFER_INTERRUPT 0x03u

#define U16_LO(value) ((uint8_t)((value) & 0xffu))
#define U16_HI(value) ((uint8_t)(((value) >> 8u) & 0xffu))

const uint8_t pwt_usb_device_descriptor[PWT_USB_DEVICE_DESCRIPTOR_LENGTH] = {
    18, USB_DESC_DEVICE,
    0x00, 0x02,
    PWT_USB_CLASS_WIRELESS_CONTROLLER,
    PWT_USB_BTH_SUBCLASS,
    PWT_USB_BTH_PROTOCOL_PRIMARY_CONTROLLER,
    64,
    U16_LO(PWT_USB_VID), U16_HI(PWT_USB_VID),
    U16_LO(PWT_USB_PID), U16_HI(PWT_USB_PID),
    0x00, 0x01,
    1, 2, 3,
    1,
};

const uint8_t pwt_usb_configuration_descriptor[PWT_USB_CONFIGURATION_DESCRIPTOR_LENGTH] = {
    9, USB_DESC_CONFIGURATION,
    U16_LO(PWT_USB_CONFIGURATION_DESCRIPTOR_LENGTH),
    U16_HI(PWT_USB_CONFIGURATION_DESCRIPTOR_LENGTH),
    1, 1, 0, 0x80, 50,

    9, USB_DESC_INTERFACE,
    0, 0, 3,
    PWT_USB_CLASS_WIRELESS_CONTROLLER,
    PWT_USB_BTH_SUBCLASS,
    PWT_USB_BTH_PROTOCOL_PRIMARY_CONTROLLER,
    4,

    7, USB_DESC_ENDPOINT,
    PWT_USB_EP_EVENT_IN, USB_TRANSFER_INTERRUPT,
    U16_LO(PWT_USB_EVENT_EP_SIZE), U16_HI(PWT_USB_EVENT_EP_SIZE),
    1,

    7, USB_DESC_ENDPOINT,
    PWT_USB_EP_ACL_IN, USB_TRANSFER_BULK,
    U16_LO(PWT_USB_ACL_EP_SIZE), U16_HI(PWT_USB_ACL_EP_SIZE),
    1,

    7, USB_DESC_ENDPOINT,
    PWT_USB_EP_ACL_OUT, USB_TRANSFER_BULK,
    U16_LO(PWT_USB_ACL_EP_SIZE), U16_HI(PWT_USB_ACL_EP_SIZE),
    1,
};
